import type { Metadata } from "next";
import { raleway, roboto } from "./fonts";
import "./globals.css";
import HeadNav from "@/components/HeadNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${raleway.variable} ${roboto.variable}`}>
      <body>
        <HeadNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
