import type { Metadata } from "next";
import { raleway, roboto } from "./fonts";
import "./globals.css";
import HeadNav from "@/components/HeadNav";
import Footer from "@/components/Footer";
import StyledComponentsRegistry from "@/components/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${raleway.variable} ${roboto.variable}`}>
      <body>
        <StyledComponentsRegistry>
          <HeadNav />
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
